### PR TITLE
Fix: #76. Reformat yaml files using update_schema.py

### PR DESCRIPTION
**Pull request by ioggstream**
## This PR

- enforces `risk` and `implementation` as lists

## It is done

- using the provided python script
- the script is provided as a tool for validating the refactor
  but it can be removed if you think.

## Notes

The PHP application should already support `risk` and `implementation` as lists

### CODE REVIEW

**Comment by wurstbrot** [comment]
@ioggstream will you maintain _.py_ files, even in 4 years?

**Comment by ioggstream** [comment]
When we are done with reformatting, we can drop them

**Comment by wurstbrot** [comment]
Some sentences are not correctly formated, I changed it manually.

**Comment by ioggstream** [comment]
I'll check them, thanks!

**Pull request merged**
