### PR TITLE
Overlay for Comprehensive Heatmap

### PR DESCRIPTION
**Pull request by ptechofficial**
This PR is dealing with issue #192 

Will be creating an overlay which would look something like this:
image

### CODE REVIEW

**Comment by wurstbrot** [comment]
Hi @ptechofficial ,

as soon as you are done, please remove "WIP" and request a review from @0x41head and me.

**Comment by wurstbrot** [comment]
I feel the removed console logs are helpful. Why remove?

**Comment by 0x41head** [comment]
Agreed. Alternatively, we can create a production branch, which doesn't log anything.

**Comment by wurstbrot** [comment]
> Agreed. Alternatively, we can create a production branch, which doesn't log anything.

What do you mean by "product branch"? You mean a feature toggle for debugging which is disabled by default and enabled in development?

**Comment by 0x41head** [comment]
> What do you mean by "product branch"? You mean a feature toggle for debugging which is disabled by default and enabled in development?

That could work as well, but I was thinking more in the lines of having a separate branch that doesn't log anything and people could use that if they wanted a more "clean" build of DSOMM

**Comment by ptechofficial** [comment]
There are a few console logs that were commented on. Should I keep them as well?

**Comment by wurstbrot** [comment]
> There are a few console logs that were commented out. Should I keep them as well?

yes please

**Review by wurstbrot — APPROVED** [review]

**Review by 0x41head — APPROVED** [review]

**Review by 0x41head — APPROVED** [review]
LGTM :+1:

**Pull request merged**
