### PR TITLE
Display uuid on task description

### PR DESCRIPTION
**Pull request by ivareri**
Display UUID in task description. 

(UUID's added in https://github.com/wurstbrot/DevSecOps-MaturityModel/pull/243)

### CODE REVIEW

**Review by wurstbrot — APPROVED** [review]

**Review by wurstbrot — CHANGES_REQUESTED** [review]
Please fix errors in https://github.com/wurstbrot/DevSecOps-MaturityModel/actions/runs/5776836226/job/15678900620?pr=245

**Comment by ivareri** [comment]
All tests should succeed now

**Review by wurstbrot — APPROVED** [review]

**Comment by wurstbrot** [comment]
thank you @ivareri . Are you able to sign your commits?
In case it is too much work, I will merge this time.

**Comment by ivareri** [comment]
Ahh, if you cloud merge this time it would be faster. Probably won't have time before next weekend to figure out signing

**Pull request merged**
