### PR TITLE
fix #199

### LINKED ISSUE #199: Cannot see full Circle Graph
Expected:

I expect to see the full graph when on the 'circular-heatmap' page

Actual:

I do not see the full graph when on the 'circular-heatmap' page

### PR DESCRIPTION
**Pull request by jkingdon-ms**
Can now view the full graph, fixing Issue #199 

Screenshot 2023-01-20 at 5 28 49 PM

### CODE REVIEW

**Comment by jkingdon-ms** [comment]
@wurstbrot

**Comment by wurstbrot** [comment]
Hi @jkingdon-ms , the display of the spiderweb with heatmap depends on the screensize. What about the middle, e.g. 70%?

**Comment by jkingdon-ms** [comment]
hey @wurstbrot , I've tested it out, seems to work at 70% too so i've change to that setting.

**Comment by wurstbrot** [comment]
thank you

**Pull request merged**
