### PR TITLE
Added schemas for validation of DSOMM yamls

### PR DESCRIPTION
**Pull request by Tamronimus**
Hello @wurstbrot 

What do you think about this approach?
Thanks to the definition of the schema, certain schematic errors can be recognised directly (if you have yaml validation in the IDE).
If I have time soon, I can look into some of these errors.

### CODE REVIEW

**Comment by Tamronimus** [comment]
Hi
I fixed the easy errors detected by the schema, mostly duplicate keys and typos.

**Review by wurstbrot — APPROVED** [review]

**Comment by wurstbrot** [comment]
great, thank you!

**Comment by wurstbrot** [comment]
In the long run, we should implement a quality gate in github actions validating the yamls

**Comment by Tamronimus** [comment]
Hi @wurstbrot 
I signed the commits, but i made a mistake and it created new commit id's, can you please merge this PR for me. In future changes i will sign the commits directly. Sorry for that.

**Comment by wurstbrot** [comment]
thx

**Pull request merged**
