### PR TITLE
Activity Tag filter - adding multi select component

### PR DESCRIPTION
**Pull request by ptechofficial**
image

The tags like automotable and vulnerability-assessment are being added using options variable eg.
image

But only the first two values are available in the values list.

### CODE REVIEW

**Comment by ptechofficial** [comment]
@wurstbrot @0x41head Please check it out.

**Comment by 0x41head** [comment]
@ptechofficial 
Lazy loading [link](https://stackoverflow.com/questions/61081227/my-array-is-not-empty-but-array-length-returns-0) for your reference:

**Comment by ptechofficial** [comment]
For now, I have added a reset button that will reload the page and all the tags will be enabled. I will try to make it work without reloading the page.

**Comment by wurstbrot** [comment]
This branch will be closed?

**Comment by ptechofficial** [comment]
Yes, we can close this.

**Comment by wurstbrot** [comment]
close due to #231

**Pull request closed without merging**
